
# Taller de Clasificación y Regresión



Elaborado por:
    
Luis Octavio González Salcedo

Diplomado en Inteligencia Artificial y Aprendizaje Profundo.



## 1. Importación de Índices


In [3]:

import tensorflow as tf ##importación de tensorflow

import pathlib ##importación del módulo pathlib
import os ##importación del módulo os
import matplotlib.pyplot as plt ##importación de matplotlib
import pandas as pd ##importación de pandas
import numpy as np ##importación de numpy

from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

##configura las opciones de impresión
##Estas opciones determinan la forma en que se muestran los números de punto flotante, las matrices y otros objetos NumPy.
##En este caso, usa el parámetro de precisión, que corresponde al número de dígitos de precisión para salida de punto flotante.
np.set_printoptions(precision=4)




## 2. Construcción de una Red Neuronal Artificial de Regresión para predicción del Precio de las Viviendas



### 2.1. Conjunto de Datos


El Conjunto de Datos de Boston tiene 506 filas y 14 columnas. Este Conjuntos de Datos contiene las siguientes columnas [[1]](https://www.kaggle.com/c/boston-housing):

crim: corresponde a la tasa de criminalidad per cápita por ciudad.

zn: corresponde a la proporción de terreno residencial dividido en zonas para lotes de más de 25,000 pies cuadrados.

indus: corresponde a la proporción de acres comerciales no minoristas por ciudad.

chas: corresponde a la variable ficticia de Charles River (= 1 si el tramo limita con el río; 0 en caso contrario).

nox: corresponde a la concentración de óxidos de nitrógeno (partes por 10 millones).

rm: corresponde al número medio de habitaciones por vivienda.

age: corresponde a la proporción de unidades ocupadas por sus propietarios construidas antes de 1940.

dis: corresponde a la media ponderada de las distancias a cinco centros de empleo de Boston.

rad: corresponde al índice de accesibilidad a carreteras radiales.

tax: corresponde a la tasa de impuesto a la propiedad de valor total por cada $ 10,000.

ptratio: corresponde a la proporción alumno-profesor por ciudad.

black: corresponde a 1000(Bk - 0.63)^2, donde Bk es la proporción de población afrodescendiente por ciudad.

lstat: corresponde al estatus más bajo de la población (porcentaje).

medv: corresponde al valor medio de las viviendas ocupadas por sus propietarios en cada $ 1000.

Este conjunto de datos es referido por:

    Harrison, D. and Rubinfeld, D.L. (1978) Hedonic prices and the demand for clean air. J. Environ. Economics and Management 5, 81–102.

    Belsley D.A., Kuh, E. and Welsch, R.E. (1980) Regression Diagnostics. Identifying Influential Data and Sources of Collinearity. New York: Wiley.



Para la descarga del Conjunto de Datos, se usa el siguiente código [[2]](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html):


In [13]:

from sklearn.datasets import load_boston
X, y = load_boston(return_X_y = True)
print(X.shape)
print(y.shape)


(506, 13)
(506,)


In [17]:

D = X
data2 = D
print(data2.shape)
print(data2)


(506, 13)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [18]:

print(y.shape)
print(y)


(506,)
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.


In [19]:

y1 = np.transpose(y)
print(y1.shape)
print(y1)


(506,)
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.



### 2.2. Descripción del Proyecto



Este proyecto se desarrolla para evaluar el rendimiento y la potencia predictiva de un modelo entrenado y probado sobre datos referentes al mercado inmobiliario residencial en barrios de Boston. Una vez se consigue un buen buen ajuste, se puede utilizar el modelo para predecir el precio de viviendas en ese área. La importancia de un modelo así, es su aplicación para una agencia inmobiliaria que puede hacer uso de la información proporcionada diariamente. Se usa la guía disponible en [[3]](https://medium.com/datos-y-ciencia/proyecto-machine-learning-predicci%C3%B3n-de-precios-de-viviendas-en-boston-con-regresi%C3%B3n-e8655e6c3655).



Dado que el objetivo del entrenamiento es desarrollar un modelo que tenga la capacidad de predecir el valor de las viviendas, se dividirá el conjunto de datos en las características y la variable objetivo, y se almacenarán en las variables ‘features’ and ‘prices’, respectivamente.

Las características ‘RM’, ‘LSTAT’ y ‘PTRATIO’, dan información cuantitativa acerca de cada entrada. Se almacenarán en “features”.

La variable objetivo, ‘MEDV’, será la variable que se desea predecir, y se almacenará en “prices”.



Se procede inicialmente a la eliminación de datos de las columnas que contienen información sobre las variables que no se desean, que están en las columnas 0, 1, 2, 3, 4, 6, 7, 8, 9, 11 de data2:


In [23]:

data3 = np.delete(data2, (0,1,2,3,4,6,7,8,9,11), axis=1)
print(data3.shape)
print(data3)


(506, 3)
[[ 6.575 15.3    4.98 ]
 [ 6.421 17.8    9.14 ]
 [ 7.185 17.8    4.03 ]
 ...
 [ 6.976 21.     5.64 ]
 [ 6.794 21.     6.48 ]
 [ 6.03  21.     7.88 ]]


In [38]:

features = data3
prices = y



### 2.3. Elaboración de la Red Neuronal Artificial



Los modelos en Keras se definen como una secuencia de capas. Se creamos un modelo secuencial y se añaden capas una a una hasta que la topología de red satisface el resultado de la predicción (precisión). Lo primero que se hace es asegurar de que la capa de entrada tiene el número correcto de entradas. Esto se puede especificar al crear la primera capa con el argumento input_dim y establecerlo para las variables de entrada.

En este caso de estudio, se utiliza una estructura de red conectada con tres capas. Las capas completamente conectadas se densifican utilizando la clase Dense. Se puede especificar el número de neuronas en la capa como el primer argumento y especificar la función de activación usando el argumento de activación. Se usa la función de activación del rectificador (relu) en las dos primeras capas y la función de activación sigmoide en la capa de salida. Antes las funciones de activación sigmoide y tanh eran preferidas para todas las capas. Hoy en día, se observa un mejor rendimiento utilizando la función de activación del rectificador [[4]](https://unipython.com/desarrolla-primera-red-neural-python-keras-paso-paso/).


In [39]:

##Fijación de las semillas aleatorias para la reproducibilidad:
np.random.seed(7)

##Creación del modelo:
model = Sequential()
model.add(Dense(20, input_dim=3, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))



Ahora que el modelo está definido, se puede compilar. La compilación del modelo utiliza las eficientes librerías numéricas de backend como Theano o TensorFlow. El backend elige automáticamente la mejor manera de representar la red para entrenar y hacer predicciones para que se ejecuten en su hardware, como CPU o GPU o incluso distribuidas.

Al compilar, se deben especificar algunas propiedades adicionales necesarias para la formación de la red. Entrenar una red significa encontrar el mejor conjunto de pesos para hacer predicciones para este problema. Se debe especificar la función de pérdida a utilizar para evaluar un conjunto de pesos, el optimizador utilizado para buscar a través de diferentes pesos para la red y cualquier métrica opcional que se quisiera recopilar y reportar durante el entrenamiento.

En este caso de estudio, se utilizará el error cuadrático medio, que es la función más comúnmente utilizada para un problema de  regresión y se define en Keras como “mse”. También utilizaremos como algoritmo de optimización el RMSprop que está diseñado para redes neuronales.

Finalmente, debido a que no es un problema de clasificación, los indicadores de evaluación utilizados en los problemas de regresión también son diferentes, por lo que el concepto de precisión no se aplica y en este caso se recopila y se reporta el error absoluto medio (mae) como la métrica.


In [42]:

##Compilación del modelo:
model.compile(loss='mse', optimizer='rmsprop', metrics=['mae'])


In [45]:

##Importar libreria para la separación de los datos de entrenamiento:
from sklearn.model_selection import train_test_split
##Utilizar 25% de los Datos para Entrenar los Modelos:
X_train, X_test, Y_train, Y_test = train_test_split(features, prices, test_size =0.25, random_state = 0)

print(X_train.shape)
print(X_train)

print(X_test.shape)
print(X_test)

print(Y_train.shape)
print(Y_train)

print(Y_test.shape)
print(Y_test)


(379, 3)
[[-0.9682  0.298   0.814 ]
 [-0.5095  0.5754 -0.4812]
 [ 1.3995 -0.3956 -0.9256]
 ...
 [-0.3756 -0.3031 -0.3298]
 [-0.3628 -0.2569  0.8616]
 [-1.0153 -0.8579  0.2855]]
(127, 3)
[[ 6.8904e-02 -7.1922e-01 -7.4475e-01]
 [-9.7781e-02  8.0658e-01 -4.3777e-01]
 [ 1.2589e-01 -9.5040e-01 -3.0180e-01]
 [-1.3330e+00  8.0658e-01  9.9761e-01]
 [-7.4986e-02  1.1303e-01 -4.3883e-02]
 [-6.4200e-01  1.1765e+00 -5.8636e-01]
 [-5.4085e-01  8.0658e-01 -1.6864e-01]
 [-4.5110e-01  8.0658e-01 -4.7141e-01]
 [-1.8686e+00 -2.5677e-02 -1.8311e-03]
 [ 1.7148e-01  1.1302e+00 -2.8358e-01]
 [-4.6677e-01  8.0658e-01  1.1168e+00]
 [ 5.3049e-01  8.0658e-01  1.2009e+00]
 [ 8.0302e-02  8.0658e-01  7.2006e-01]
 [-2.3259e+00  8.0658e-01  2.1905e+00]
 [ 2.1617e+00 -1.7364e+00 -1.5045e+00]
 [ 1.0776e+00 -1.6902e+00 -1.1092e+00]
 [-6.0739e-02  8.0658e-01 -2.6816e-01]
 [ 1.4280e+00 -2.7074e+00 -1.2017e+00]
 [ 3.7236e-01 -8.5793e-01 -1.0265e+00]
 [-6.1921e-01  3.4421e-01 -5.4430e-01]
 [ 2.0140e-01  5.2916e-01 -7.6438e

In [49]:

train_data = X_train
train_targets = Y_train
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data = X_test
test_data -= mean
test_data /= std

test_targets = Y_test

def smooth_curve (puntos, factor = 0.9):
        smoothed_points = []
        for point in points:
            if smoothed_points:
                previous = smoothed_points[-1]
                smoothed_points.append(previous * factor + point * (1 - factor))
            else:
                smoothed_points.append(point)
        return smoothed_points


model.fit(train_data,train_targets,epochs=80,batch_size=16,verbose=0)
test_mse_score,test_mae_score=model.evaluate(test_data,test_targets)
print(test_mae_score)


4/4 [==============================] - 0s 5ms/step - loss: 535.6574 - mae: 21.3063
21.30630111694336
